// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhongThiNghiem.Models;

namespace PhongThiNghiem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201015023646_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhongThiNghiem.Models.BaiThiNgiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaiThiNgiems");
                });

            modelBuilder.Entity("PhongThiNghiem.Models.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("PhieuMuonId")
                        .HasColumnType("int");

                    b.Property<int>("ThietBiId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("PhieuMuonId", "ThietBiId");

                    b.HasIndex("ThietBiId");

                    b.ToTable("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("PhongThiNghiem.Models.GV_BaiThiNghiem", b =>
                {
                    b.Property<int>("BaiTNId")
                        .HasColumnType("int");

                    b.Property<int>("GVId")
                        .HasColumnType("int");

                    b.HasKey("BaiTNId", "GVId");

                    b.HasIndex("GVId");

                    b.ToTable("GV_BaiThiNghiems");
                });

            modelBuilder.Entity("PhongThiNghiem.Models.GiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenGV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("PhongThiNghiem.Models.LoaiThietBi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiTB")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("LoaiThietBis");
                });

            modelBuilder.Entity("PhongThiNghiem.Models.PhieuMuon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DaTra")
                        .HasColumnType("bit");

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.ToTable("PhieuMuons");
                });

            modelBuilder.Entity("PhongThiNghiem.Models.ThietBi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiThieBiId")
                        .HasColumnType("int");

                    b.Property<string>("TenTB")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiThieBiId");

                    b.ToTable("ThietBis");
                });

            modelBuilder.Entity("PhongThiNghiem.Models.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("PhongThiNghiem.Models.PhieuMuon", "PhieuMuon")
                        .WithMany()
                        .HasForeignKey("PhieuMuonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhongThiNghiem.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("ThietBiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhongThiNghiem.Models.GV_BaiThiNghiem", b =>
                {
                    b.HasOne("PhongThiNghiem.Models.BaiThiNgiem", "BaiThiNgiem")
                        .WithMany("GiaoViens")
                        .HasForeignKey("BaiTNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhongThiNghiem.Models.GiaoVien", "GiaoVien")
                        .WithMany("BaiThiNgiems")
                        .HasForeignKey("GVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhongThiNghiem.Models.PhieuMuon", b =>
                {
                    b.HasOne("PhongThiNghiem.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhongThiNghiem.Models.ThietBi", b =>
                {
                    b.HasOne("PhongThiNghiem.Models.LoaiThietBi", "LoaiThietBi")
                        .WithMany("ThietBis")
                        .HasForeignKey("LoaiThieBiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
